# playbook to onboard a new tenant including
# - a base folder structure required by the tenant
# - a Ranger HDFS policy defining permissions on those tenant folders
#
# Supported vars:
# - `hosts`: target host or inventory group
#
# Example run:
# ansible-playbook  deploy-tenant-on-cdp.yml  -i $INVENTORY --diff -v
#
- hosts: "{{ hosts | default('edge') }}"
  # gather_facts required for the "ansible_fqdn" fact (required by a kerberos_kinit role var)
  gather_facts: yes
  become: yes
  run_once: true

  tasks:
    - name: do kinit (via role)
      block:
        - include_role:
            name: kerberos_kinit
          vars:
            kerberos_kinit_keytab_type: cdh
            kerberos_kinit_realm: "{{ kerberos_realm }}"
            kerberos_kinit_user: "{{ hdfs_root_user }}"
      when:
        - kerberos_realm is defined
        - do_kinit | default(True) | bool
      tags: 
        - kinit
        - hdfs-folders

    - name: deploying hdfs folders for all tenants
      block:
        - name: deploying hdfs base folders for tenant {{ item.tenant }}
          include_role:
            name: ansible-hdfs-dirs
          vars:
            hdfs_dirs_list: "{{ item.hdfs_folders | default(hdfs_folders) }}"
            hdfs_dir_default_become_user: "{{ hdfs_root_user }}"
            tenant: "{{ item.tenant }}"
          loop: "{{ hdfs_folder_tenants }}"
      tags: 
        - hdfs-folders
      when:
        - hdfs_folder_tenants is defined

    - import_role:
        name: ranger_modules
      tags: 
        - ranger-hdfs
        - ranger

    - name: deploy Ranger HDFS policies for all tenants
      block:
        - name: deploy Ranger HDFS policies for tenant {{ item.tenant }}
          vars:
            deploy_hdfs_dirs: "{{ ranger_tenants }}"
            tenant: "{{ item.tenant }}"
          ranger_hdfs_policies:
            state: present
            admin_url: "{{ ranger_admin_url }}"
            admin_username: "{{ ranger_admin_username }}"
            admin_password: "{{ ranger_admin_password }}"
            policies: "{{ ranger_hdfs_policies }}"
          loop: "{{ ranger_tenants }}"
      tags: 
        - ranger-hdfs
        - ranger
      when:
        - ranger_hdfs_policies is defined
