## Playbook to install postgresql 9.6 from the offical postgres (pgdg) repo using `geerlingguy.postgresql` role
# Notes:
# - the role is expected to be in a configured role path (usually added via git submodule)
# - the target server host should not run selinux (in mode enforcing), as this might create issues
#
- hosts: all
  gather_facts: true
  become: yes
  pre_tasks:
    # Note: Deploying below repo only on CentOS, since RHEL usually runs only on customer servers (with centrally managed repositories)
    - name: install PostgreSQL 9.6 repository
      yum:
        name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
        state: present
      when: ansible_distribution == 'CentOS'
    - debug: 
        var: postgresql_hba_entries
        verbosity: 1
        
  roles:
    #- name: geerlingguy.postgresql
    - name: ansible-role-postgresql
      postgresql_enablerepo: "pgdg96"
      postgresql_version: 9.6
      postgresql_data_dir: /var/lib/pgsql/9.6/data
      postgresql_bin_path: /usr/pgsql-9.6/bin
      postgresql_config_path: /var/lib/pgsql/9.6/data
      postgresql_daemon: postgresql-9.6.service
      postgresql_packages:
        - postgresql96
        - postgresql96-server
        - postgresql96-libs
        - postgresql96-contrib
        - postgresql96-devel
